version:  '3.8'

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: