version:  '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
    ports:
      - 9000:9000
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - mynetwork
    restart: always
  nginx:
    build:
     context: ./requirements/nginx
     dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - 443:443
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - mynetwork
    restart: always

volumes:
  mariadb_data:
    # driver: local 
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /Users/yel-moun/data/mariadb
  wordpress_data:
    # driver: local 
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /Users/yel-moun/data/wordpress

networks:
  mynetwork:
    driver: bridge