version:  '3.8'

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
    ports:
      - 9000:9000
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - mynetwork
  nginx:
    build:
     context: ./nginx
     dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - mynetwork

volumes:
  mariadb_data:
  wordpress_data:

networks:
  mynetwork:
    driver: bridge